#server:
#  port: 8082

spring:
  application:
    name: activity-service
  config:
    import: optional:configserver:http://localhost:8888
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/fitnessactivity
#      database: fitnessactivity
#  eureka:
#    client:
#      register-with-eureka: true
#      fetch-registry: true
#      serviceUrl:
#        defaultZone: http://localhost:8761/
#
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#rabbitmq:
#  exchange:
#    name: fitness.exchange
#  queue:
#    name: activity.queue
#  routing:
#    key: activity.tracker
#
