
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888





#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/api/users/**
#
#        - id: ai-service
#          uri: lb://AI-SERVICE
#          predicates:
#            - Path=/api/recommendation/**
#
#        - id: activity-service
#          uri: lb://ACTIVITY-SERVICE
#          predicates:
#            - Path=/api/activity/**
#
#
#    eureka:
#      client:
#        register-with-eureka: true
#        fetch-registry: true
#        serviceUrl:
#          defaultZone: http://localhost:8761/